spring.application.name=titishop-backend
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
server.compression.enabled=true
server.compression.mime-types=application/json,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
server.compression.min-response-size=1024
app.frontend-public-url=${FRONTEND_PUBLIC_URL:https://titishop.proyectoutp.com}
app.public-url=${APP_PUBLIC_URL:https://api-titishop.proyectoutp.com}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://127.0.0.1:4200,https://titishop.proyectoutp.com,https://www.titishop.proyectoutp.com}
app.upload.dir=${APP_UPLOAD_DIR:uploads}
app.upload.public-url=${APP_UPLOAD_PUBLIC_URL:${app.public-url}/uploads}
app.upload.max-file-size=${APP_UPLOAD_MAX_FILE_SIZE:5MB}
app.jwt.issuer=titishop-backend
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=120
app.factiliza.api-token=${FACTILIZA_API_TOKEN:}
app.factiliza.api-base-url=${FACTILIZA_API_BASE_URL:https://api.factiliza.com/v1}
app.factiliza.connect-timeout=${FACTILIZA_CONNECT_TIMEOUT:3s}
app.factiliza.read-timeout=${FACTILIZA_READ_TIMEOUT:6s}
springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED:false}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED:false}
springdoc.swagger-ui.path=/swagger-ui.html
spring.servlet.multipart.max-file-size=${APP_UPLOAD_MAX_FILE_SIZE:5MB}
spring.servlet.multipart.max-request-size=${APP_UPLOAD_MAX_REQUEST_SIZE:6MB}
